-- MySQL Script generated by MySQL Workbench
-- Mon Dec 18 13:01:43 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Medewerker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medewerker` (
  `id` INT NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `tussenvoegsel` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `telefoon` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Klant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klant` (
  `id` INT NOT NULL,
  `voornaam` VARCHAR(45) NOT NULL,
  `tussenvoegsel` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `telefoon` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specialiteit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specialiteit` (
  `id` INT NOT NULL,
  `naam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Behandeling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Behandeling` (
  `Code` VARCHAR(4) NOT NULL,
  `naam` VARCHAR(45) NOT NULL,
  `duur` VARCHAR(45) NOT NULL,
  `prijs` INT NOT NULL,
  PRIMARY KEY (`Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Afspraak`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Afspraak` (
  `Datum_tijd` DATETIME NOT NULL,
  `Klant_id` INT NOT NULL,
  `Medewerker_id` INT NOT NULL,
  PRIMARY KEY (`Klant_id`, `Datum_tijd`),
  INDEX `fk_Afspraak_Klant1_idx` (`Klant_id` ASC),
  INDEX `fk_Afspraak_Medewerker1_idx` (`Medewerker_id` ASC),
  CONSTRAINT `fk_Afspraak_Klant1`
    FOREIGN KEY (`Klant_id`)
    REFERENCES `mydb`.`Klant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Afspraak_Medewerker1`
    FOREIGN KEY (`Medewerker_id`)
    REFERENCES `mydb`.`Medewerker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medewerker_has_specialiteit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medewerker_has_specialiteit` (
  `specialiteit_id` INT NOT NULL,
  `medewerker_id` INT NOT NULL,
  PRIMARY KEY (`specialiteit_id`, `medewerker_id`),
  INDEX `fk_Specialiteit_has_Medewerker_Medewerker1_idx` (`medewerker_id` ASC),
  INDEX `fk_Specialiteit_has_Medewerker_Specialiteit_idx` (`specialiteit_id` ASC),
  CONSTRAINT `fk_Specialiteit_has_Medewerker_Specialiteit`
    FOREIGN KEY (`specialiteit_id`)
    REFERENCES `mydb`.`Specialiteit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specialiteit_has_Medewerker_Medewerker1`
    FOREIGN KEY (`medewerker_id`)
    REFERENCES `mydb`.`Medewerker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Afspraak_has_Behandeling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Afspraak_has_Behandeling` (
  `Afspraak_Klant_id` INT NOT NULL,
  `Afspraak_Datum_tijd` DATETIME NOT NULL,
  `Behandeling_Code` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`Afspraak_Klant_id`, `Afspraak_Datum_tijd`, `Behandeling_Code`),
  INDEX `fk_Afspraak_has_Behandeling_Behandeling1_idx` (`Behandeling_Code` ASC),
  INDEX `fk_Afspraak_has_Behandeling_Afspraak1_idx` (`Afspraak_Klant_id` ASC, `Afspraak_Datum_tijd` ASC),
  CONSTRAINT `fk_Afspraak_has_Behandeling_Afspraak1`
    FOREIGN KEY (`Afspraak_Klant_id` , `Afspraak_Datum_tijd`)
    REFERENCES `mydb`.`Afspraak` (`Klant_id` , `Datum_tijd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Afspraak_has_Behandeling_Behandeling1`
    FOREIGN KEY (`Behandeling_Code`)
    REFERENCES `mydb`.`Behandeling` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
